### ISSUE TITLE
Изучить составление дневника астматика

### ISSUE THREAD

**Issue by mkudmi** [AlexDesmos/TTP-21.10#1]
Необходимо собрать информацию по дневнику астматика:

1. Какую информацию необходимо записывать?
2. В каком формате записывается информация?
3. Какую еще информацию можно полезно записывать в дневник?
4. Как долго ведется дневник?

После этого составить список основного функционала для веб-приложения исходя из списка параметров в дневнике, записать в отдельный файл.

**Comment by AlexDesmos** [comment]
1. **Показатели пикфлоуметрии** (л/мин) днем и вечером
2. В виде таблиц, где столбцы это дни, разбитые на двое времени суток, а строки, это показатели пикфлоуметрии
3. Наличие кашля, макроты, сложности дыхания, тяжести в легких и свист при речи. Также применение лекарств и таблеток, а также их дозы и названия. Требуется кол-во вдохов в минуту, переносимость физ. нагрузки и состояние после нее.
4. Дневник ведется всю жизнь, если врожденная астма, и с получения болезни, при приобретенной.
[https://spulmo.ru/upload/kr/BA_2021.pdf](url)

**Comment by FeCoRTFee** [comment]
3. Возможность подгружать выписки, направления, показания из поликлиник или больниц. 
4. Возможность добавления информации по приёму лекарств на прошлые дни, если пациент забыл это сделать.
5. Учет кол-ва ингаляторов за промежуток времени.

**Comment by FeCoRTFee** [comment]
*Уведомления: забыл принять лекарства, забыл записать какую то информацию в дневник.
